FROM wyveo/nginx-php-fpm:php73

LABEL MAINTAINER duongductrong06@gmail.com 

# RUN apt-get update
# RUN apt-get -y install curl

# Install Composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash && \ 
#     apt-get -y install nodejs

# RUN npm install
# RUN composer install